from typing import TextIO
from .. import deserializer, deserialize,add_deserializer, get_name, is_clone
from .controller_common import controller_deserialize, create_internal

add_deserializer("camera", create_internal("Scene.gameplayCamera"))
add_deserializer("combo", create_internal("Scene.combo"))
add_deserializer("scoreTitle", create_internal("Scene.scoreTitle"))
add_deserializer("score", create_internal("Scene.score"))
add_deserializer("predictedGrade", create_internal("Scene.predictedGrade"))
add_deserializer("predictedGradeBg", create_internal("Scene.predictedGradeBackground"))
add_deserializer("jacket", create_internal("Scene.jacket"))
add_deserializer("jacketBg", create_internal("Scene.jacketBackground"))
add_deserializer("title", create_internal("Scene.title"))
add_deserializer("composer", create_internal("Scene.composer"))
add_deserializer("diff", create_internal("Scene.difficultyText"))
add_deserializer("diffBg", create_internal("Scene.difficultyBackground"))
add_deserializer("hud", create_internal("Scene.hud"))
add_deserializer("info", create_internal("Scene.infoPanel"))
add_deserializer("pause", create_internal("Scene.pauseButton"))
add_deserializer("bg", create_internal("Scene.Background"))
add_deserializer("videobg", create_internal("Scene.videoBackground"))
add_deserializer("singlelinel", create_internal("Scene.singleLineL"))
add_deserializer("singleliner", create_internal("Scene.singleLineR"))
add_deserializer("beatlines", create_internal("Scene.beatlines"))
add_deserializer("skyinputline", create_internal("Scene.skyInputLine"))
add_deserializer("skyinputlabel", create_internal("Scene.skyInputLabel"))
add_deserializer("darken", create_internal("Scene.darken"))
add_deserializer("track", create_internal("Scene.track"))
add_deserializer("divline01", create_internal("Scene.track.divideLine01"))
add_deserializer("divline12", create_internal("Scene.track.divideLine12"))
add_deserializer("divline23", create_internal("Scene.track.divideLine23"))
add_deserializer("divline34", create_internal("Scene.track.divideLine34"))
add_deserializer("divline45", create_internal("Scene.track.divideLine45"))
add_deserializer("critline0", create_internal("Scene.track.criticalLine0"))
add_deserializer("critline1", create_internal("Scene.track.criticalLine1"))
add_deserializer("critline2", create_internal("Scene.track.criticalLine2"))
add_deserializer("critline3", create_internal("Scene.track.criticalLine3"))
add_deserializer("critline4", create_internal("Scene.track.criticalLine4"))
add_deserializer("critline5", create_internal("Scene.track.criticalLine5"))
add_deserializer("edgeextraL", create_internal("Scene.track.edgeExtraL"))
add_deserializer("edgeextraR", create_internal("Scene.track.edgeExtraR"))
add_deserializer("extraL", create_internal("Scene.track.extraL"))
add_deserializer("extraR", create_internal("Scene.track.extraR"))
